"$schema" = 'https://starship.rs/config-schema.json'

#Eine neue Zeile vor jedem neuen Promt einfÃ¼gen
add_newline = true





format = """
$username \
in\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 0
truncation_symbol = 'â€¦/'
truncate_to_repo = true
home_symbol = " ğŸ "


[username]
show_always = true
format = "[$user]($style)"

[character]
success_symbol = "[â¯](green)"
error_symbol = "[â¯](red)"

[cmd_duration]
min_time=1
show_milliseconds=true

[fill]
style=' '
